### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by thislooksfun** [mludowise/ARKitRectangleDetection#11]
Hello,

I found this project from [here](https://stackoverflow.com/a/45539121/3438793), and I just had a quick question about the license. The `License.txt` file says that it is MIT, but the source files ([eg](https://github.com/mludowise/ARKitRectangleDetection/blob/master/ARKitRectangleDetection/PlaneRectangle.swift)) say `Copyright © 2017 Mel Ludowise. All rights reserved.` Which license is the project under?

Thanks,
-tlf

**Comment by mludowise** [comment]
The license is MIT. You’re free to copy this, modify it, and do whatever you want this source.

-Mel

________________________________

**Comment by thislooksfun** [comment]
Excellent, thank you!
