### ISSUE TITLE
Non-horizontal planes

### ISSUE THREAD

**Issue by yeldarby** [mludowise/ARKitRectangleDetection#3]
Great work; any thoughts on how to make this work with non-horizontal planes? For example, a picture on the wall or a computer screen?

I know ARKit only does horizontal plane detection. But trying to figure out if this might be possible to deduce from the 4 corners, the position of the camera, and the distance to an `ARHitTestResult.featurePoint` at the midpoint of the rectangle.

**Comment by mludowise** [comment]
Since ARKit doesn't currently support vertical planes, you could potentially use featurePoints but you would need to do some math to filter them down to only points that exist on the same vertical plane.

I would do this by updating `getCorners` in `PlaneRectangle.swift` to:
```
    let tlHit = sceneView.hitTest(sceneView.convertFromCamera(rectangle.topLeft), types: .featurePoint).first
    let trHit = sceneView.hitTest(sceneView.convertFromCamera(rectangle.topRight), types: .featurePoint).first
    let blHit = sceneView.hitTest(sceneView.convertFromCamera(rectangle.bottomLeft), types: .featurePoint).first
    let brHit = sceneView.hitTest(sceneView.convertFromCamera(rectangle.bottomRight), types: .featurePoint).first

if onVerticalPlane(tlHit, trHit, blHit) {
  return .bottomRight(topRight: trHit.worldVector,
                               bottomLeft: blHit.worldVector,
                               bottomRight: brHit.worldVector)
} else if onVerticalPlane(tlHit, trHit, brHit) {
  ...
} else if onVerticalPlane(tlHit, blHit, brHit) {
  ...
} else if onVerticalPlane(trHit, blHit, brHit) {
  ...
} else {
  return nil
}
```

You would need to write a function `onVerticalPlane` that determines if the plane defined by the worldVector for each hit is vertical.

Alternatively, if you don't care that the rectangle is actually vertical, you could instead use the plane determined by 3 of the corners. You would need to calculate the transform needed to display the SCNPlane at the right angle.

It does, however, seem like [Apple is going to update ARKit to include vertical plane detection](https://stackoverflow.com/questions/44422118/how-to-detect-vertical-planes-in-arkit), so you might want to wait.

**Comment by yeldarby** [comment]
Just wanted to update that I got a hacky version of this working by using featurePoints and just assuming that they're on the same plane if they're the corners of the detected rectangle. Took a while to get the right roll/pitch/yaw values and it's kind of hacky but it works

Unfortunately I've completely mangled all the code so it's not in a state where I can submit a PR but at least it's a viable lead!

**Comment by mludowise** [comment]
Awesome!

**Comment by mludowise** [comment]
@yeldarby If you got a "hacky" version of non-horizontal plane detection but don't have the time to clean it up for a PR, I'd still be interested in seeing the source as a gist so I could play with it.

P.S. I saw you got a lot of Twitter engagement on your sudoku solver release. Congrats!

**Comment by yeldarby** [comment]
Thanks!

I think most of what I changed was in `PlaneRectangle.swift`

I think these are the important parts:
```
fileprivate func getCornersWithPoints(for rectangle: VNRectangleObservation, in sceneView: ARSCNView) -> (corners: RectangleCorners, anchor: ARPlaneAnchor?)? {
    // Perform a hittest on each corner to find intersecting surfaces
    let tl = sceneView.hitTest(sceneView.convertFromCamera(rectangle.topLeft), types: .featurePoint)
    let tr = sceneView.hitTest(sceneView.convertFromCamera(rectangle.topRight), types: .featurePoint)
    let bl = sceneView.hitTest(sceneView.convertFromCamera(rectangle.bottomLeft), types: .featurePoint)
    
    let hitResultAnchorComparator: (ARHitTestResult, ARHitTestResult) -> Bool = { (hit1, hit2) in
        return true
    }
    
    
    var surfaces = filterByIntersection([tl, tr, bl], where: hitResultAnchorComparator)
    if let tlHit = surfaces[0].first,
        let trHit = surfaces[1].first,
        let blHit = surfaces[2].first {
        return (.topLeft(topLeft: tlHit.worldVector,
                         topRight: trHit.worldVector,
                         bottomLeft: blHit.worldVector),
                nil)
    }
    
    return nil
}
```
I also added a `VerticalOrientation` property to PlaneRectangle that can then be used in `RectangleNode` instead of hard coding it to `-Float.pi/2`
```
 init?(for rectangle: VNRectangleObservation, in sceneView: ARSCNView) {
        var cornersAndAnchor = getCorners(for: rectangle, in: sceneView)
        var anchoredToPlane = true

        if(cornersAndAnchor == nil) {
            cornersAndAnchor = getCornersWithPoints(for: rectangle, in: sceneView)
            anchoredToPlane = false
        }
        
        if(cornersAndAnchor == nil) {
            return nil
        }
        
        let corners = cornersAndAnchor!.corners
        
        self.anchor = cornersAndAnchor!.anchor
        self.position = corners.center
        self.size = CGSize(width: corners.width, height: corners.height)
        self.orientation = corners.orientation
        
        if(!anchoredToPlane) {
            var v = sceneView.session.currentFrame!.camera.eulerAngles[0]*2/Float.pi
            v = -abs(v.rounded())*Float.pi/2            
            self.verticalOrientation = v
        }
    }
```

**Comment by mludowise** [comment]
Thank you! When I get some free time, I’m going to see if I can make some updates.

**Comment by yeldarby** [comment]
Quick update: I reworked the code a bit and think I may have a more reliable solution than calculating `orientation` and `verticalOrientation`.

I'm now using all 4 corners of the `RectangleObservation` with `featurePoints` to derive a `center` and `top` (top-center) position and to get the width and height.

```
struct RectangleCorners {
    var topLeft:SCNVector3
    var topRight:SCNVector3
    var bottomLeft:SCNVector3
    var bottomRight:SCNVector3
}

extension RectangleCorners {
    // Returns width based on average width of top and bottom of the rectangle
    var width: CGFloat {
        get {
            let topWidth = topRight.distance(from: topLeft)
            let bottomWidth = bottomRight.distance(from: bottomLeft)
            
            return (topWidth + bottomWidth)/2
        }
    }
    
    // Returns height based on average height of the left and right of the rectangle
    var height: CGFloat {
        get {
            let leftHeight = topLeft.distance(from: bottomLeft)
            let rightHeight = topRight.distance(from: bottomRight)
            
            return (leftHeight + rightHeight)/2
        }
    }
    
    // Returns the top center of the rectangle by averaging top center and negative bottom center vectors
    var top: SCNVector3 {
        get {
            let top1 = topLeft.midpoint(from: topRight)
            
            let center = self.center
            let bottom = bottomLeft.midpoint(from: bottomRight)
            let v = bottom - center
            let top2 = center - v
            
            return (top1 + top2) / 2
        }
    }
    
    // Returns the midpoint by averaging the four corners of the rectangle
    var center: SCNVector3 {
        return (topLeft + topRight + bottomLeft + bottomRight) / 4
    }
}
```

And then I'm using these two positions in `RectangleNode` with SceneKit's `look(at:)` method to do the orientation:

```
var transform = SCNMatrix4MakeTranslation(center.x, center.y, center.z)
transform = SCNMatrix4Scale(transform, width, height)
self.transform = transform
self.look(at: top)
```

This seems to work pretty well no matter if the detected Rectangle is on a horizontal plane or not.

There is one axis of rotation that's not very well defined it seems like with `look(at:)`; but it works close enough most of the time. Going to try to figure out how to get that one working better in the future but just wanted to leave an update with my progress in case you're still working on this repo.

**Comment by ldenoue** [comment]
would you mind posting the code for vertical planes?
ARKit now supports vertical planes, but the code as is creates the overlays at the wrong position in 3D space (it only works well for horizontal planes).
I've tried changing SCNMatrix4MakeRotation in RectangleNode.init, but can't find a proper way to make the node flat on a vertical plane anchor.
